robot:
  name: yuanli
  parameters:
    left_arm:
      joint_positions:
        type: vector
        calibrate: true
        detect: true
      ee_position:
        type: vector
        calibrate: true
        detect: true
      ee_orientation:
        type: quaternion
        calibrate: true
        detect: true
      gripper:
        type: scalar
        calibrate: true
        detect: true
    right_arm:
      joint_positions:
        type: vector
        calibrate: true
        detect: true
      ee_position:
        type: vector
        calibrate: true
        detect: true
      ee_orientation:
        type: quaternion
        calibrate: true
        detect: true
      gripper:
        type: scalar
        calibrate: true
        detect: true

home_position:
  right_arm:
    joint_positions:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    ee_position:
    - 0.0
    - 0.0
    - 0.0
    ee_orientation:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    gripper: 0.0
  left_arm:
    joint_positions:
    - -0.8694887161254883
    - -0.26569774746894836
    - -0.0867009162902832
    - 1.5323660373687744
    - 0.3397887647151947
    - -1.5578402280807495
    ee_position:
    - 0.1981883943080902
    - -0.22991710901260376
    - 0.1723204404115677
    ee_orientation:
    - -0.007636182941496372
    - 0.010934026911854744
    - -0.4154171049594879
    - 0.9095332622528076
    gripper: 0.00029247622645997947

tolerances:
  right_arm:
    joint_positions: 0.15
    ee_position: 0.05
    ee_orientation: 0.1
    gripper: 0.01
  left_arm:
    joint_positions: 0.15
    ee_position: 0.05
    ee_orientation: 0.1
    gripper: 0.01
