robot: Quanta_x1
mode: calibrated
fail_mode: any

data:
  raw_path: /mnt/public/dht/fold_towel

calibration:
  data_path: /mnt/public/dht/fold_towel
  exclude_episodes: [
    # episode_0002,
    # episode_0005
   ]
  tolerance_factor: 3.0
