fixed_home_position:
  right_arm:
    joint_positions:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    gripper: 0.0
    ee_position:
    - 0.2
    - 0.0
    - 0.5
    ee_orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  left_arm:
    joint_positions:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    gripper: 0.0
    ee_position:
    - 0.2
    - 0.0
    - 0.5
    ee_orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0

thresholds:
  max_joint_error: 0.15
  gripper_error: 0.01
  ee_position_error: 0.05
  ee_orientation_error: 0.1
